language: node_js
node_js: "8"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
script:
  - ./scripts/run_python_tests.sh
  - ./scripts/build_and_lint_all
  - if [ "$BROWSERSTACK_KEY" ]; then yarn test-travis; fi
