cache: yarn
matrix:
  include:
    - language: node_js
      node_js:
        - "8"
        - "10"
      script:
        - yarn build
        - yarn lint
        - yarn test-travis
      cache: yarn
      git:
        depth: 5

    - language: node_js
      node_js: "8"
      stage: integ
      script:
        - echo 'yarn test-integ is disabled currently (https://github.com/tensorflow/tfjs/issues/679)'
      git:
        depth: 5
